
package cl.subtel.interop.cntv.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu May 11 16:17:13 GMT-03:00 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "agregarUsuario", namespace = "http://cntv.interop.subtel.cl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "agregarUsuario", namespace = "http://cntv.interop.subtel.cl/", propOrder = {"arg0", "arg1", "arg2"})

public class AgregarUsuario {

    @XmlElement(name = "usuario")
    private cl.subtel.interop.cntv.dto.UsuarioDTO arg0;
    @XmlElement(name = "empresa")
    private cl.subtel.interop.cntv.dto.EmpresaDTO arg1;
    @XmlElement(name = "representante")
    private cl.subtel.interop.cntv.dto.RepresentanteLegalDTO arg2;

    public cl.subtel.interop.cntv.dto.UsuarioDTO getArg0() {
        return this.arg0;
    }

    public void setArg0(cl.subtel.interop.cntv.dto.UsuarioDTO newArg0)  {
        this.arg0 = newArg0;
    }

    public cl.subtel.interop.cntv.dto.EmpresaDTO getArg1() {
        return this.arg1;
    }

    public void setArg1(cl.subtel.interop.cntv.dto.EmpresaDTO newArg1)  {
        this.arg1 = newArg1;
    }

    public cl.subtel.interop.cntv.dto.RepresentanteLegalDTO getArg2() {
        return this.arg2;
    }

    public void setArg2(cl.subtel.interop.cntv.dto.RepresentanteLegalDTO newArg2)  {
        this.arg2 = newArg2;
    }

}

