
package cl.subtel.interop.cntv.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu May 11 16:17:13 GMT-03:00 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "recibirCarpetaTecnicaResponse", namespace = "http://cntv.interop.subtel.cl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirCarpetaTecnicaResponse", namespace = "http://cntv.interop.subtel.cl/")

public class RecibirCarpetaTecnicaResponse {

    @XmlElement(name = "return")
    private cl.subtel.interop.cntv.dto.RespuestaDTO _return;

    public cl.subtel.interop.cntv.dto.RespuestaDTO getReturn() {
        return this._return;
    }

    public void setReturn(cl.subtel.interop.cntv.dto.RespuestaDTO new_return)  {
        this._return = new_return;
    }

}

